### ISSUE TITLE
Prepare Backups (step 4)

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/docs-pcf-install#192]
If the backups are disabled, the prepare backup node is automatically set to 0, when it must be one.  Something isn't correct here - either the docs are wrong or there are more steps.

**Comment by bentarnoff** [comment]
Hey @agregory999 thanks for this. Can you clarify which topic and which version of the documentation you're looking at? Thanks.

**Comment by agregory999** [comment]
Step 4 where it says to disable automatic backups.   Appears you need them enabled to get the backup prepare node...

-Andrew

Andrew Gregory
617-529-0749 | agregory@pivotal.io


Transforming how the world builds software.

**Comment by bentarnoff** [comment]
Since we have multiple backup topics (BBR and non-BBR), and multiple versions of those topics (1.12, 1.11, etc.), and GitHub issues are repo-wide, we won't be able to address this until we know the **title of the topic** and the **version of the topic** you're looking at.

**Comment by pspinrad** [comment]
Am guessing it's here:
https://docs.pivotal.io/pivotalcf/1-12/customizing/backup-restore/backup-pcf-bbr.html#backup-prepare-node

Docs say you need to enable the backup prepare node in order to enable automated MySQL backups, which in turn enables BBR.

Then they say you enable backups by selecting *Disable automated backups*, which seems wrong.

Then they tell you to scale Backup Prepare Node to 1 instance and show it scaled to 0 instances, which seems wrong.

**Comment by thereses** [comment]
@pspinrad @agregory999 the docs are correct. in 1.12 ERT added the ability to deploy the backup-prepare node without setting up automated backups of ERT.
