### ISSUE TITLE
AWS AMI ID for US-EAST-2 not available in Cloud Formation template

### ISSUE THREAD

**Issue by msathe-tech** [pivotal-cf/docs-pcf-install#289]
hello,

I'm trying to follow instructions to setup first PCF on AWS using the docs below - 
https://docs.pivotal.io/pivotalcf/1-12/customizing/cloudform-template.html

The link to download the Cloud Formation template for 1.12.x is below - 

https://network.pivotal.io/products/elastic-runtime#/releases/9710

This template doesn't have the AMI ID for us-east-2. 

This caused error while using the Cloud Formation template. 

Regards,
Madhav

**Comment by seviet** [comment]
@evanfarrar Would you be able to comment on this CloudFormation issue? Thanks!!

**Comment by ljarzynski** [comment]
Hi @msathe-tech, thanks for filing this issue! 

After talking to our Infrastructure team, I found out that there is no reason why us-east-2 should not be included, but it's possible it is not in the JSON because it did not exist at the time this particular CloudFormation template was made. 

If you still want to use the template in us-east-2, you could modify the json slightly by adding another mapping. The image below contains the AMI ID for us-east-2. I found it by:
1- Locating and copying the AMI ID for us-east-1 in the cloudformation json 
2- Opening my EC2 dashboard (us-east-1 region) and searching for that AMI ID
3- Copying the corresponding AMI name
4- Switching my console to us-east-2 and searching for the same AMI name

![screen shot 2018-01-08 at 2 30 21 pm](https://user-images.githubusercontent.com/16656416/34695753-e73b173a-f480-11e7-9dbe-6ee8b878af5f.png)

cc @evanfarrar This is the first time we've had a user report this issue, but it may be worth adding the other regions in case.

**Comment by msathe-tech** [comment]
It is still not there, following are the available regions -
  "Description": "CloudFormation template for configuring Pivotal Cloud Foundry on AWS",
  "Mappings": {
    "NATRegionToAmiMap" : {
      "us-east-1" : {
        "id" : "ami-303b1458"
      },
      "us-west-1" : {
        "id" : "ami-7da94839"
      },
      "us-west-2" : {
        "id" : "ami-69ae8259"
      },
      "eu-west-1" : {
        "id" : "ami-6975eb1e"
      },
      "eu-central-1" : {
        "id" : "ami-46073a5b"
      },
      "ap-southeast-1" : {
        "id" : "ami-b49dace6"
      },
      "ap-northeast-1" : {
        "id" : "ami-03cf3903"
      },
      "ap-southeast-2" : {
        "id" : "ami-e7ee9edd"
      },
      "sa-east-1" : {
        "id" : "ami-fbfa41e6"
      }
    }
  },
