### ISSUE TITLE
Which security group is recommended as the `Default Security Group`?

### ISSUE THREAD

**Issue by bingosummer** [pivotal-cf/docs-pcf-install#403]
In https://github.com/pivotal-cf/docs-pcf-install/blob/2.1/azure-om-config.html.md.erb, which security group is recommended as the `Default Security Group`?
In https://github.com/pivotal-cf/pcf-azure-arm-templates, there are two security groups.
In https://docs.pivotal.io/pivotalcf/2-1/customizing/azure-arm-template.html#deploy, a third security group `pcf-nsg` is created.

**Comment by bingosummer** [comment]
CC: @mxplusb

**Comment by mxplusb** [comment]
@bingosummer the ARM templates are a bit out of date (my fault) and aren't our defacto deployment engine for Azure. We are using [terraforming-azure](https://github.com/pivotal-cf/terraforming-azure) as our default deployment engine. Whatever is created from terraform would be considered the standard. This is primarily because the CF folks are trying to maintain one tool overall instead of one per IaaS (CloudFormation, ARM templates, Cloud Deployment Manager on GCP, etc). @evanfarrar is leading that charge, so he is a good PoC around our terraforming efforts.

I do have an open work item on my end to migrate/update the ARM template to match the terraform output. As part of that work, I do have to go through and make sure the documentation is up to date. But I'm short handed for now. I do fully intend to update it, I'm just not sure when that will happen.

//cc: @cwsteve2117 @boparp-pivotal

**Comment by bingosummer** [comment]
Thanks @mxplusb for your quick response.
I can't wait to test the terraforming-azure which is awesome.
When I follow the [doc](https://docs.pivotal.io/pivotalcf/2-1/customizing/azure-deploy-terraform.html#download), I find the terraform template is not yet published in PivNet.
FYI: https://github.com/pivotal-cf/docs-pcf-install/issues/382

**Comment by mxplusb** [comment]
Yeah, the docs need a massive overhaul, to be honest. Let me see what the long-term plans are and see if I can start a work stream on it.

**Comment by mlimonczenko** [comment]
Hello @bingosummer and @mxplusb,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
