### ISSUE TITLE
Error while installing 'Small FootPrint PAS' on AWS manually

### ISSUE THREAD

**Issue by harisonde** [pivotal-cf/docs-pcf-install#446]
Hi Team,

I am trying to install PCF 2.0 on AWS and getting a below error while performing step to install 'Installing Small Footprint PAS' as a part of 'Small FootPrint PAS' installation.

Error Message:- 

"Task 128 | 16:27:26 | Preparing deployment: Preparing deployment (00:00:01)
                    L Error: Colocated job 'bosh-dns-aliases' is already added to the instance group 'database'.
Task 128 | 16:27:27 | Error: Colocated job 'bosh-dns-aliases' is already added to the instance group 'database'."

And i have attached complete error logs(Pls check error logs.txt)

All the steps till 'Installing Small Footprint PAS' completed successfully and having an issue during this step. 

I have tried to re install it by choosing 'Disable BOSH DNS server for troubleshooting purposes' on bosh director config but still no luck and facing the same issue.

Can you please look into it and let me know why this error occurring?

[error_logs.txt](https://github.com/pivotal-cf/docs-pcf-install/files/2195103/error_logs.txt)
[error_logs.txt](https://github.com/pivotal-cf/docs-pcf-install/files/2195104/error_logs.txt)

**Comment by pspinrad** [comment]
Thank you for raising this issue, and I'm sorry that you are having trouble. Please sign in to [Pivotal Support](https://support.pivotal.io) and consult the community or open a case. See [Pivotal Support for Subscribers](https://content.pivotal.io/support/pivotal-support-for-subscribers) for how to do this.

If Pivotal Support's investigation determines that this is a general problem, rather than an issue that is fairly specific to your situation, we will update the documentation.

**Comment by pareschi** [comment]
Hi Harisonde,
I'm facing the same issue. Have you solved this problem?

Thanks,
Luiz
