### ISSUE TITLE
404 Not Found: Requested route when accessing PCF Apps manager

### ISSUE THREAD

**Issue by NateMay** [pivotal-cf/docs-pcf-install#555]
**Describe the bug**
My PCF Apps Manager is not accessible

**To Reproduce**
1. Logged into my account
2. Selected the Apps Tab
3. Clicked "PCF Apps Manager button"
4. Error: 404 Not Found: Requested route ('apps.cfapps-gt1.nam.nsroot.net') does not exist.

**Expected behavior**
Access to Apps manager

**OS, Browser, and Version:**
 - Chrome

**Additional context**
I can still access and launch apps from the command line

**Comment by pspinrad** [comment]
Thank you for raising this issue, and I'm sorry that you are having trouble. Please sign in to [Pivotal Support](https://support.pivotal.io) and consult the community or open a case. See [Pivotal Support for Subscribers](https://content.pivotal.io/support/pivotal-support-for-subscribers) for how to do this.
If Pivotal Support's investigation determines that this is a general problem, rather than an issue that is fairly specific to your situation, we will update the documentation.
