### ISSUE TITLE
azure-arm-template does not create pcf-nsg

### ISSUE THREAD

**Issue by DaxterM** [pivotal-cf/docs-pcf-install#98]
It looks like the arm template @ http://docs.pivotal.io/azure-deploy-parameters.json called out in step 3 of http://docs.pivotal.io/pivotalcf/1-8/customizing/azure-arm-template.html  does not create the pcf-nsg network security group that is required for ops man to deploy bosh. These steps are in the manual instructions @ http://docs.pivotal.io/pivotalcf/1-8/customizing/azure-om-deploy.html step 1 

Following http://docs.pivotal.io/pivotalcf/1-8/customizing/azure-prepare-env.html followed by http://docs.pivotal.io/pivotalcf/1-8/customizing/azure-arm-template.html and http://docs.pivotal.io/pivotalcf/1-8/customizing/azure-om-config.html will result in an error that the security group does not exists when saving the azure config in ops man

**Comment by hpejcinovic-pivotal** [comment]
+1 to what @DaxterM said.

**Comment by seviet** [comment]
Hi @DaxterM thanks for reporting this! we're looking into this.

**Comment by seviet** [comment]
@DaxterM and @hpejcinovic-pivotal - apologies for the enormous delay. Wanted to update you (if you do not know already) that the ARM templates are located here https://github.com/pivotal-cf/pcf-azure-arm-templates and you may want to report any issues (if still existing) on that repo since the docs team does not maintain the templates themselves.
